# Site settings
title: Welcome Back
email: me@marktareshawty.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marktareshawty.com" # the base hostname & protocol for your site
twitter_username: tarebyte
github_username:  tarebyte

# Build settings
markdown: kramdown
sass:
  style: compressed
