# Permalink
permalink: /posts/:title/

name: marktareshawty.com
url: https://marktareshawty.com

author:
  name: Mark Tareshawty
  email: mark@marktareshawty.com

sass:
  sass_dir: _scss
  style: compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-feed

exclude:
  - script
  - Gemfile
  - Gemfile.lock
  - vendor
