# Permalink
permalink: /posts/:title/

# Setup
title: Mark Tareshawty
url: "http://marktareshawty.com/"
description: >
  This is the corner of the Internet that contains Mark Tareshawty's musings
  and semi-tolerable jokes.
basename: ""
author:
  name: Mark Tareshawty
  email: mark@marktareshawty.com

# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
  style: compressed

# Custom Vars
github:
  repo:           https://github.com/tarebyte/tarebyte.github.io
handle: tarebyte
