# Site settings
title: Welcome Back
email: mark@marktareshawty.com
description: >
  This is the corner of the Internet that contains Mark Tareshawty's musings
  and semi-tolerable jokes.
url: "http://marktareshawty.com/" # the base hostname & protocol for your site
twitter_username: tarebyte
github_username:  tarebyte
email_address: me@marktareshawty.com

permalink: /posts/:title/

# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
  style: compressed
